In [14]:
import numpy as np

First Task

In [20]:
#Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

Second Task

In [30]:
arr = np.arange(16)
arr[1:16].reshape(3,5).T


array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

Third Task

In [33]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
np.setdiff1d(a,b)

array([ 1,  7,  8, 15])

Fourth Task

Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a NumPy array wherein you can record the cumulative miles you recorded each day during your trip. Then use your Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West. Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your approach to this problem, including the ways in which you decided to make use of NumPy.

In [35]:
#1610 miles and 136 hrs 11.8 miles/hr - Based on the google map, the distance is 1,610 miles and it will take 136 hours by bicycle
array = (60, 110, 150, 200, 250, 300, 350, 390, 450, 500, 500, 580, 650, 710, 800, 850, 900, 960, 960, 1000, 1050, 1100, 1150, 1150, 1200, 1280, 1330, 1400, 1400, 1440, 1500, 1530, 1570, 1590, 1610)
# I assume I will be riding for 5 or 6 hours per day and if I'm a good condition, I will be driven more than 6 hours. 
np.diff(array)
# Below is the total miles per day by using 'diff' function. Since there might be 4 non-consecutive days due to the weather or condition, I randomly put it in my array and it indicates '0' in here.


array([50, 40, 50, 50, 50, 50, 40, 60, 50,  0, 80, 70, 60, 90, 50, 50, 60,
        0, 40, 50, 50, 50,  0, 50, 80, 50, 70,  0, 40, 60, 30, 40, 20, 20])

Fifth Task

In [36]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

In [39]:
#What is the maximum yearly NYC consumption of water in millions of gallons per day?
np.max(nyc_water[:, 2]) # Using np.max function and get the result

1512.0

In [46]:
#How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
x = np.shape(nyc_water[:]) # Using shape funcion and remove the second column
x[0]

39

In [50]:
# What is the mean and the standard deviation of the per capita daily water consumption?
# Using mean and std funcion and get the result
x = np.mean(nyc_water[:, 3])
y = np.std(nyc_water[:, 3])

print(x)
print(y)

160.30769230769232
31.51894330370624


In [51]:
#What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

np.diff(nyc_water[:, 1]) # Using diff function and slice the row and column

array([-30461. ,  17602. ,  19864. ,  72119. ,  53290. ,  39540. ,
        45192. ,  23230. ,  11243. ,  -9544. ,  -8525. ,  38851. ,
        54443. ,  77222. ,  64292. ,  62582. ,  64772. ,  75631. ,
        84816. ,  89401. ,  60618. ,  16685.5,  16685.5,  16685.5,
        16685.5,  16685.5,  16685.5,  16685.5,  16685.5,  16685.5,
        16685.5, 108965. ,  77081. ,  61281. ,  49530. ,  44512. ,
        21171. ,  85025. ])